import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-[family-name:var(--font-geist-mono)]`}
      >
        <header className="sticky top-0 p-4 bg-black flex justify-between">
          <h1 className="text-xl">
            Sorting Algorithms
          </h1>

          <div>Selection Sort</div>

          <div>
            for other stuff
          </div>
        </header>

        <main className="py-6 px-4 items-center flex justify-center items-center">
          {children}
        </main>
        
        <footer className="absolute bottom-0 left-0 right-0 p-4 flex gap-6 flex-wrap items-center justify-center">
          controls | input size | etc
        </footer>
      </body>
    </html>
  );
}
