import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface SubtopicProps {
  title: string;
  path: string;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const subtopics: SubtopicProps[] = [
    {
      title: "Selection Sort",
      path: "/sorting/selection-sort"
    },
    {
      title: "Bubble Sort",
      path: "/sorting/bubble-sort"
    },
    {
      title: "Insertion Sort",
      path: "/sorting/insertion-sort"
    },
    {
      title: "Merge Sort",
      path: "/sorting/merge-sort"
    },
    {
      title: "Quick Sort",
      path: "/sorting/quick-sort"
    },
  ];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-[family-name:var(--font-geist-mono)]`}
      >
        <header className="sticky top-0 p-4 z-10 bg-black">
          <h1 className="text-xl">
            Sorting Algorithms
          </h1>
        </header>

        <div className="absolute z-10">
          <ul>
          {subtopics.map((item: SubtopicProps, index) => {
            return <li key={'subtopic'+index}>
            <Link  
              className="px-4"
              href={item.path}
            >
              {item.title}
            </Link></li>
          })}
          </ul>
        </div>

        <main className="mx-4 relative"
          style={{ height: "85vh" }}
        >
          {children}
        </main>
      </body>
    </html>
  );
}
